name: Playwright Tests
on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.47.0-jammy
    steps:
    - uses: actions/checkout@v4
    - name: Set Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: yarn
    - name: Run install
      uses: borales/actions-yarn@v5
      with:
        cmd: install
    - run: cd loama
    - name: Build repo
      uses: borales/actions-yarn@v5
      with:
        cmd: build
    - name: Install Playwright Browsers
      uses: borales/actions-yarn@v5
      with:
        cmd: playwright install --with-deps
        dir: loama
    - name: Run playwright tests
      uses: borales/actions-yarn@v5
      with:
        cmd: test
        dir: loama
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: loama/playwright-report/
        retention-days: 30
